version: '3'
services:
    postgres:
        image: postgres:11.1
        restart: on-failure
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASS}
        volumes:
            - ./database:/docker-entrypoint-initdb.d/:ro
    transaction-server:
        build: transaction-server
        depends_on:
            - postgres
        restart: unless-stopped
        ports:
            - ${TRANSACTION_PORT}:5000
        volumes:
            - ./transaction-server/out:/out:rw
        environment:
            - PYTHONUNBUFFERED=TRUE
