version: '3'
services:
  nginx:
      build: ./nginx
      tty: true
      ports:
          - '80:80'
      networks:
        - nginx_network

  workload-generator:
      build: ./workload-generator
      stdin_open: true
      tty: true
      environment:
          - STATS=1
          - NUM_THREADS=10
      volumes:
          - ./workload-generator/src:/src
          - ./workload-generator/workloads:/workloads
      networks:
          - nginx_network

networks:
  nginx_network:
    driver: bridge