version: '3'
services:
    adminer:
        image: michalhosna/adminer:4.7.0
        depends_on:
            - postgres
        restart: on-failure
        ports:
            - ${ADMINER_PORT}:8080
        environment:
            - ADMINER_DRIVER=pgsql
            - ADMINER_DB=postgres
            - ADMINER_SERVER=postgres
            - ADMINER_USERNAME=${DB_USER}
            - ADMINER_PASSWORD=${DB_PASS}
            - ADMINER_AUTOLOGIN=1
    postgres:
        build: database
        restart: on-failure
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASS}
        volumes:
            - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    transaction-server:
        build: transaction-server
        depends_on:
            - postgres
        restart: unless-stopped
        ports:
            - ${TRANSACTION_PORT}:5000
        volumes:
            - ./transaction-server/out:/out:rw
        environment:
            - PYTHONUNBUFFERED=TRUE
    workload-generator:
        build: workload-generator
        restart: on-failure
        depends_on:
            - transaction-server
        volumes:
            - ./workloads:/workloads:ro
        stdin_open: true
        tty: true
