version: '3'
services:
    postgres:
        build: database
        restart: on-failure
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASS}
        volumes:
            - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    transaction-server:
        build: transaction-server
        depends_on:
            - postgres
        restart: unless-stopped
        ports:
            - ${TRANSACTION_PORT}:5000
        volumes:
            - ./transaction-server/out:/out:rw
        environment:
            - PYTHONUNBUFFERED=TRUE
    workload-generator:
        build: workload-generator
        restart: on-failure
        depends_on:
            - transaction-server
        volumes:
            - ./workloads:/workloads:ro
        stdin_open: true
        tty: true
