#! /bin/bash

# Exit early if no argument provided.
if [[ $# -eq 0 ]]
then
    echo "Must provide workload filepath."
    exit 1
fi

# For macOS compatibility.
realpath() {
    [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
}

SCRIPT_PATH="/src/build/libs/http-workload-generator-1.0-SNAPSHOT.jar"
RELATIVE_DIR=$(dirname "$0")
ABSOLUTE_DIR=$(realpath "$RELATIVE_DIR")
WORKLOADS_DIR="$ABSOLUTE_DIR/workloads"
YML_PATH="$ABSOLUTE_DIR/docker-compose.yml"

# This assumes there is no file extension on the workload file.
WORKLOAD_NAME=$(basename -- "$1")
WORKLOAD_PATH="/workloads/$WORKLOAD_NAME"

# Find the container to attach to.
CONTAINER_REGEX="^.*workload-generator.*"
CONTAINER_NAME=$(sudo docker-compose -f "$YML_PATH" top | grep "$CONTAINER_REGEX")

if [[ -z "$CONTAINER_NAME" ]]
then
    echo "Must run container first."
    exit 1
fi

echo "Generator running, press Ctrl+\\ to exit."

sudo docker exec \
    -it \
    "$CONTAINER_NAME" \
java -jar "$SCRIPT_PATH" "$WORKLOAD_PATH"
